require("seth.plugins-setup")
require("seth.core.options")
require("seth.core.keymaps")
require("seth.core.colorscheme")
require("seth.plugins.nvim-tree")
require("seth.plugins.lualine")
require("seth.plugins.nvim-cmp")
require("seth.plugins.lsp.mason")
require("seth.plugins.lsp.lspconfig")
require("seth.plugins.autopairs")
require("seth.plugins.treesitter")
require("seth.plugins.gitsigns")
require("seth.plugins.telescope")
require("seth.plugins.leap")
require("seth.plugins.overseer")
require("seth.plugins.yapf")
require("seth.plugins.comment")
require("seth.plugins.presence")
-- require("seth.plugins.auto-dark-mode")
require("seth.plugins.barbar")
require("seth.plugins.java")
require("seth.plugins.dap")
require("seth.plugins.neoscroll")
require("seth.plugins.copilot")
require("seth.plugins.conform")
require("seth.plugins.snacks")
require("seth.plugins.sidekick")

-- vim.g.vimspector_enable_mappings = 'HUMAN'
if vim.fn.executable("python3") == 1 then
  vim.g.python3_host_prog = vim.fn.exepath("python3")
end
